import { connect, waitForPageLoad } from "@/client.js";

// Connect to the browser
const client = await connect();
const page = await client.page("real-ai-e2e");

console.log("Navigating to app...");
await page.goto("http://localhost:5173");
await waitForPageLoad(page);

// Helper function to send message
async function sendMessage(text) {
  await page.waitForSelector("textarea");
  await page.fill("textarea", text);
  await page.click("button:has(svg.lucide-send)");
  // Wait for AI response (bubble appears)
  await page.waitForTimeout(1000); 
}

// 1. Test TodoWrite (Planning)
console.log("Testing Task Planning...");
await sendMessage("Please create a plan to learn Go concurrency using TodoWrite tool.");

console.log("Waiting for Task Panel...");
try {
  await page.waitForSelector("text=Plan & Progress", { timeout: 45000 });
  console.log("✅ Task Panel visible - TodoWrite called by Real LLM");
} catch (e) {
  console.error("❌ Task Panel not found");
  // Log body text for debug
  const body = await page.textContent("body");
  console.log("Page Content:", body.slice(0, 500));
}

// 2. Test Subagent (Task)
console.log("Testing Subagent...");
await sendMessage("Please delegate a task to 'explore' agent to find the current Go version using the Task tool.");

console.log("Waiting for Subagent execution...");
try {
  await page.waitForSelector("text=Subagent:", { timeout: 45000 });
  console.log("✅ Subagent execution visible - Task tool called by Real LLM");
} catch (e) {
  console.error("❌ Subagent execution not found");
}

// 3. Test Skill Loading
console.log("Testing Skill Loading...");
await sendMessage("Please load the 'golang-best-practices' skill using the Skill tool.");

console.log("Waiting for Skill Loading...");
try {
  await page.waitForSelector("text=Skill Loaded", { timeout: 45000 });
  console.log("✅ Skill Loading visible - Skill tool called by Real LLM");
} catch (e) {
  console.error("❌ Skill Loading not found");
}

// 4. Test Sandbox Mode (Bash)
console.log("Testing Sandbox Mode...");
await sendMessage("Write a simple hello world go program and execute it using bash.");

console.log("Waiting for Sandbox Tag...");
try {
  await page.waitForSelector("text=Sandbox Mode", { timeout: 60000 }); // Longer timeout for code gen
  console.log("✅ Sandbox Mode tag visible - Bash block generated by Real LLM");
} catch (e) {
  console.error("❌ Sandbox Mode tag not found");
}

console.log("Test Complete.");
await client.disconnect();
